# Generated by Django 5.1.2 on 2024-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, default='Sfoto.jpg', upload_to=''),
        ),
    ]
