# Generated by Django 5.1.2 on 2024-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baba',
            fields=[
                ('id_baba', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('cpf', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='responsavel',
            fields=[
                ('id_responsavel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('cpf', models.TextField(max_length=255)),
            ],
        ),
    ]
