# Generated by Django 5.1.2 on 2024-11-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='responsavel',
            new_name='Babas',
        ),
        migrations.DeleteModel(
            name='baba',
        ),
        migrations.RenameField(
            model_name='babas',
            old_name='id_responsavel',
            new_name='id_baba',
        ),
    ]
