# Generated by Django 5.1.2 on 2024-11-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_responsavel_babas_delete_baba_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Babas',
            new_name='Baba',
        ),
    ]
