# Generated by Django 5.1.2 on 2024-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
