# Generated by Django 5.1.2 on 2024-11-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baba_slug_responsavel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='foto',
            field=models.ImageField(blank=True, default='Sfoto.jpg', upload_to=''),
        ),
    ]
