# Generated by Django 5.1.2 on 2024-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_baba_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='foto',
            field=models.ImageField(blank=True, default='Sfoto.jpg', upload_to=''),
        ),
    ]
