# Generated by Django 5.1.3 on 2025-02-04 22:23

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Baba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=255)),
                ('contato', models.CharField(default='', max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='link', unique_with=('cpf', 'email', 'owner'))),
                ('habilidades', models.TextField(default='', max_length=255)),
                ('foto', models.ImageField(default='../static/images/white-square.png', upload_to='images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Resp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=255)),
                ('contato', models.CharField(default='', max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='link', unique_with=('cpf', 'email', 'owner'))),
                ('foto', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(blank=True, max_length=100)),
                ('data_contratacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_servico', models.DateField()),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='users.baba')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='users.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('periodo', models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('recorrente', models.BooleanField(default=False)),
                ('frequencia', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_recorrencia', models.DateField(blank=True, null=True)),
                ('fim_recorrencia', models.DateField(blank=True, null=True)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('baba', 'dia', 'periodo')},
            },
        ),
    ]
