# Generated by Django 5.1.2 on 2024-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Baba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
    ]
