# Generated by Django 5.1.2 on 2024-11-23 00:31

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Baba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=255)),
                ('contato', models.CharField(default='', max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='link', unique_with=('cpf', 'email', 'owner'))),
                ('habilidades', models.TextField(default='', max_length=255)),
                ('foto', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
