# Generated by Django 5.1.3 on 2025-01-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_baba',
            name='bioBaba',
            field=models.TextField(default='', max_length=255),
        ),
    ]
