# Generated by Django 5.1.3 on 2024-12-15 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('periodo', models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=20)),
                ('recorrente', models.BooleanField(default=False)),
                ('frequencia', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_recorrencia', models.DateField(blank=True, null=True)),
                ('fim_recorrencia', models.DateField(blank=True, null=True)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('baba', 'dia', 'periodo')},
            },
        ),
    ]
