# Generated by Django 5.1.3 on 2025-01-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
