# Generated by Django 5.1.3 on 2025-01-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_baba_biobaba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_baba',
            name='bioBaba',
        ),
    ]
