# Generated by Django 5.1.2 on 2024-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_baba_cpf_alter_perfil_baba_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_baba',
            name='link',
            field=models.CharField(blank=True, default=models.EmailField(max_length=255, unique=True), max_length=50),
        ),
    ]
