# Generated by Django 5.1.2 on 2024-11-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_baba_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_baba',
            name='link',
            field=models.SlugField(blank=True, default=models.EmailField(max_length=255, unique=True)),
        ),
    ]
