# Generated by Django 5.1.3 on 2025-01-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_servico_nome_responsavel'),
        ('perfis', '0003_remove_perfil_baba_biobaba'),
    ]

    operations = [
    ]
