# Generated by Django 5.1.3 on 2024-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='periodo',
            field=models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil_baba',
            name='foto',
            field=models.ImageField(default='../static/images/white-square.png', upload_to='images/'),
        ),
    ]
