# Generated by Django 5.1.3 on 2025-01-25 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_alter_agenda_periodo_alter_perfil_baba_foto'),
        ('users', '0008_merge_20241216_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_servico', models.DateField()),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='users.baba')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='users.responsavel')),
            ],
        ),
    ]
