# Generated by Django 5.1.2 on 2024-11-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_alter_perfil_baba_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_baba',
            old_name='link',
            new_name='slug',
        ),
    ]
