# Generated by Django 5.1.2 on 2024-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_rename_link_perfil_baba_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_baba',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
