# Generated by Django 5.1.2 on 2024-11-07 00:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_perfil_baba_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_baba',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil_baba',
            name='cpf',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_baba',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='link', unique_with=('cpf', 'email')),
        ),
    ]
