# Generated by Django 5.1.2 on 2024-11-07 00:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_perfil_baba_link_alter_perfil_baba_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_baba',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='link', unique_with=('cpf', 'email', 'owner')),
        ),
    ]
