# Generated by Django 5.1.2 on 2024-11-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_alter_perfil_baba_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_baba',
            name='contato',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfil_baba',
            name='habilidades',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='perfil_baba',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
