# Generated by Django 5.1.2 on 2024-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_alter_perfil_baba_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_baba',
            name='foto',
            field=models.ImageField(default='Sfoto.jpg', upload_to=''),
        ),
    ]
