# Generated by Django 5.1.2 on 2024-11-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0012_perfil_baba_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_baba',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
