# Generated by Django 5.1.2 on 2024-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0013_alter_perfil_baba_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_baba',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
