# Generated by Django 5.1.3 on 2025-02-04 22:23

import autoslug.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('numero', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique_with=['id'])),
                ('isBaba', models.BooleanField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Baba',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bioBaba', models.TextField(default='', max_length=255)),
                ('habilidades', models.TextField(default='', max_length=255)),
                ('rangeTrabalho', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'verbose_name': 'Babá',
                'verbose_name_plural': 'Babás',
                'db_table': 'users_babas',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bioResp', models.TextField()),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'db_table': 'users_responsaveis',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baba')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('servico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.servico')),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baba')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.responsavel')),
            ],
        ),
    ]
