# Generated by Django 5.1.3 on 2024-11-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='isBaba',
            field=models.BooleanField(default=True),
        ),
    ]
