# Generated by Django 5.1.2 on 2024-11-20 19:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baba',
            options={'verbose_name': 'Babá', 'verbose_name_plural': 'Babás'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.RenameField(
            model_name='baba',
            old_name='descricao',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='baba',
            old_name='data_nascimento',
            new_name='nascimento',
        ),
        migrations.RenameField(
            model_name='baba',
            old_name='numero_celular',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='descricao',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='data_nascimento',
            new_name='nascimento',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='numero_celular',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='baba',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='verificado',
        ),
        migrations.AddField(
            model_name='baba',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsavel',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baba',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterModelTable(
            name='baba',
            table='babas',
        ),
        migrations.AlterModelTable(
            name='responsavel',
            table='responsaveis',
        ),
    ]
