# Generated by Django 5.1.2 on 2024-11-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baba_options_alter_responsavel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='baba',
            table='users_babas',
        ),
        migrations.AlterModelTable(
            name='responsavel',
            table='users_responsaveis',
        ),
    ]
