# Generated by Django 5.1.2 on 2024-11-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_baba_table_alter_responsavel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baba',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='numero',
            new_name='telefone',
        ),
    ]
