# Generated by Django 5.1.3 on 2024-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_baseuser_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
