# Generated by Django 5.1.2 on 2024-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_numero_baba_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baba',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
