# Generated by Django 5.1.4 on 2024-12-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseuser_lat_baseuser_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('recorrente', models.BooleanField(default=False)),
                ('periodo', models.CharField(choices=[('matutino', 'Matutino'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='users.baba')),
            ],
            options={
                'verbose_name': 'Agenda de Trabalho',
                'verbose_name_plural': 'Agendas de Trabalho',
                'db_table': 'agenda_trabalho',
            },
        ),
    ]
