# Generated by Django 5.1.3 on 2024-12-15 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseuser_lat_baseuser_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baba')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.servico'),
        ),
    ]
