# Generated by Django 5.1.3 on 2024-12-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
