# Generated by Django 5.1.3 on 2024-11-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_baba_telefone_alter_responsavel_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.baba')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.responsavel')),
            ],
        ),
    ]
