# Generated by Django 5.1.3 on 2024-12-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_servico_avaliacao_servico'),
        ('users', '0007_delete_agenda'),
    ]

    operations = [
    ]
