# Generated by Django 5.1.3 on 2025-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20241216_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='baba',
            name='rangeTrabalho',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
