# Generated by Django 5.1.3 on 2025-02-07 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(blank=True, max_length=100)),
                ('data_contratacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_servico', models.DateField()),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='users.baba')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='users.responsavel')),
            ],
        ),
    ]
