# Generated by Django 5.1.3 on 2025-02-04 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_autor', to=settings.AUTH_USER_MODEL)),
                ('baba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_baba', to='users.baba')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_responsavel', to='users.responsavel')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
