# Generated by Django 5.1.3 on 2025-01-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
